name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Library/Library.sln

    - name: Build
      run: dotnet build ./Library/Library.sln --no-restore

    - name: Test
      run: dotnet test ./Library/Library.sln --no-build --verbosity normal
