name: .NET Core CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Library/Library.sln

    - name: Build
      run: dotnet build ./Library/Library.sln --no-restore

    - name: Test
      run: dotnet test ./Library/Library.sln --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ./Library/Library.sln -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: List Azure Web Apps
      run: az webapp list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --resource-group AlexResourceGroup --query "[].{name:name, resourceGroup:resourceGroup}" --output table

    - name: Get Secret from Key Vault
      id: get-secret
      run: |
        echo "DB_CONNECTION_STRING=$(az keyvault secret show --vault-name AlexKeysVault --name DbConnectionString --query value -o tsv)" >> $GITHUB_ENV

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: lib-web-app
        slot-name: staging
        package: ./publish
      env:
        ConnectionStrings__DefaultConnection: ${{ env.DB_CONNECTION_STRING }}
